<?xml version="1.0"?>
<package format="2">
  <name>point_cloud_projection</name>
  <version>0.0.0</version>
  <description>Colourise lidar scans and pre-built maps with calibrated camera imagery</description>
  <maintainer email="Z.Zhong@lboro.ac.uk">root</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>rospy</depend>
  <depend>rosbag</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>pcl_ros</depend>
  <depend>pcl_conversions</depend>
  <depend>roslib</depend>
  <depend>yaml-cpp</depend>

  <export>
  </export>
</package>
